name: cv_detection
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asttokens=2.0.5
  - astunparse=1.6.3
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - cmake=3.22.2
  - colorama=0.4.4
  - cryptography=36.0.0
  - cudatoolkit=10.2.89
  - dataclasses=0.8
  - decorator=5.1.1
  - executing=0.8.3
  - freetype=2.10.4
  - future=0.18.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipython=8.3.0
  - jedi=0.18.1
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.39.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-include=2022.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ninja=1.10.2
  - olefile=0.46
  - openssl=1.1.1o
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.7
  - python_abi=3.9
  - pytorch=1.8.0
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.2
  - stack_data=0.2.0
  - tk=8.6.11
  - torchaudio=0.8.0
  - torchvision=0.9.0
  - traitlets=5.1.1
  - tzdata=2021e
  - urllib3=1.26.8
  - vc=14.2 
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - cachetools==5.0.0
    - cycler==0.11.0
    - fonttools==4.29.1
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - importlib-metadata==4.11.1
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - numpy==1.22.2
    - oauthlib==3.2.0
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandas==1.4.1
    - pillow==9.0.1
    - protobuf==3.19.4
    - psutil==5.9.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.7
    - pyrealsense2==2.50.0.3812
    - pyserial==3.5
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.8.0
    - seaborn==0.11.2
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - thop==0.0.31-2005241907
    - tqdm==4.64.1
    - typing-extensions==4.1.1
    - werkzeug==2.0.3
    - zipp==3.7.0
