name: CV
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - ca-certificates=2022.9.24
  - gh=2.17.0
  - ld_impl_linux-aarch64=2.36.1
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgomp=12.1.0
  - libnsl=2.0.0
  - libstdcxx-ng=12.1.0
  - libzlib=1.2.12
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=21.3.1
  - python=3.6.15
  - python_abi=3.6
  - readline=8.1
  - setuptools=58.0.4
  - sqlite=3.38.5
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.3.0
    - backcall==0.2.0
    - cachetools==4.2.4
    - certifi==2022.5.18.1
    - cycler==0.11.0
    - cython==0.29.32
    - decorator==5.1.1
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - grpcio==1.48.2
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==3.0.3
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - numpy==1.19.4
    - oauthlib==3.2.0
    - opencv-contrib-python==4.6.0.66
    - pandas==1.1.5
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.32
    - protobuf==3.19.4
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyelftools==0.29
    - pygments==2.13.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.5.4
    - scons==4.1.0.post1
    - seaborn==0.11.2
    - serial==0.0.97
    - six==1.16.0
    - tensorboard==2.10.1
    - tensorboard-plugin-wit==1.8.1
    - thop==0.1.1-2209072238
    - torch==1.10.2
    - torchvision==0.11.3
    - traitlets==4.3.3
    - wcwidth==0.2.5
