name: cv_detection
channels:
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - decorator=5.1.1
  - executing=0.8.3
  - ipython=8.3.0
  - jedi=0.18.1
  - libcxx=12.0.0
  - libffi=3.3
  - matplotlib-inline=0.1.2
  - ncurses=6.3
  - openssl=1.1.1o
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.10.4
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tk=8.6.12
  - traitlets=5.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - charset-normalizer==2.1.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - fonttools==4.38.0
    - idna==3.4
    - kiwisolver==1.4.4
    - matplotlib==3.6.2
    - numpy==1.23.4
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.5.1
    - pillow==9.3.0
    - psutil==5.9.3
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - requests==2.28.1
    - scipy==1.9.3
    - seaborn==0.12.1
    - torch==1.13.0
    - torchvision==0.14.0
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - urllib3==1.26.12
