name: cv_detection
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - decorator=5.1.1
  - executing=0.8.3
  - ipython=8.4.0
  - jedi=0.18.1
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - matplotlib-inline=0.1.2
  - ncurses=6.3
  - openssl=1.1.1q
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.9.7
  - readline=8.1.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.2
  - stack_data=0.2.0
  - tk=8.6.11
  - traitlets=5.1.1
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==1.0.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - fonttools==4.29.1
    - future==0.18.2
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - idna==3.3
    - importlib-metadata==4.11.1
    - iso8601==1.0.2
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - numpy==1.22.2
    - oauthlib==3.2.0
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandas==1.4.1
    - pillow==9.0.1
    - protobuf==3.19.4
    - psutil==5.9.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.7
    - pyrealsense2==2.50.0.3812
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.8.0
    - seaborn==0.11.2
    - serial==0.0.97
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - thop==0.0.31-2005241907
    - torch==1.10.2
    - torchvision==0.11.3
    - tqdm==4.64.1
    - typing-extensions==4.1.1
    - urllib3==1.26.8
    - werkzeug==2.0.3
    - zipp==3.7.0
